name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker-compose build -d
    - name: Enter node app container
      run: docker exec -it app bash
    - name: Run tests
      run: npm test
